### PR TITLE
[GK-36] Score update - send info to back

### PR DESCRIPTION
**Pull request by t0maboro**
Draft, because cannot find endpoints on back.

### CODE REVIEW

**Comment by sy1wi4** [comment]
PR with backend endpoints will be merged in a while, I'm working on it.

**Comment by sy1wi4** [comment]
Endpoints are ready, should be OK now

**Comment by t0maboro** [comment]
> Endpoints are ready, should be OK now

Thanks, nice job! Probably there is still one missing, I'll need /status/{id}/points. I think I cannot do more before tomorrow evening, so it will be on time to finally connect it on the meeting.

**Comment by sy1wi4** [comment]
> > Endpoints are ready, should be OK now
> 
> Thanks, nice job! Probably there is still one missing, I'll need /status/{id}/points. I think I cannot do more before tomorrow evening, so it will be on time to finally connect it on the meeting.

You're right, I missed it. But could you clarify what exactly /status/{id}/point endpoint should be responsible for? Since we have /status/{id}/decision for changing decision, why do we need endpoint for giving points only?

**Comment by t0maboro** [comment]
Update: Displaying side referees' decisions is done - styling might need to be improved.
Something bad happens with fields allowedDecisions and fighterXPoints - still receiving [] and 0s. When it will be adjusted - the rest of things to display the score have been already prepared.

**Review by ajablonsk1 — APPROVED** [review]
Looks nice! :)

**Pull request merged**
